### ISSUE TITLE
[Proposal] Native directives for recyclable list

### ISSUE THREAD

**Issue by Hanks10100** [Hanks10100/incubator-weex#1]
## 需求背景

+ 长列表（无限列表）在移动端很常见，会消耗大量渲染时间和内存，通常是性能瓶颈。
+ 长列表中有大量节点不在可视区，回收并复用这些节点可以减少内存占用和创建新列表时的开销。
+ 在 Weex 场景下，列表的渲染由前端框架实现，原生端无法介入此渲染过程，很难实现复用。

为了提升渲染性能，可以考虑提供新的渲染长列表的方式。

## 设计方案

设计思路：

+ 前端框架中不将长列表展开，而是将列表数据和子节点的结构发送到客户端。
+ 客户端根据数据和子节点的结构渲染生成列表，并且实现节点的回收和复用。

### js 和 native 通信的数据格式

在定义列表的时候（假设是 `<list>` 组件），将把所有列表数据传递给客户端；在写列表的子组件的时候（假设是 `<cell>` 组件），会将其中添加的绑定关系发送给客户端，而不是在前端框架中展开取值。

通知 native 添加绑定的语法：

```js
{ '@binding': 'prop' }
```

凡是遇到一个带有 `@binding` 属性的对象，都将其视为动态内容；属性值是个字符串，对应了列表每条数据里的某个字段。

### 通信格式的例子

**上层语法还未确定**，本例子只是用来说明 js 和 native 直接的通信格式。

```html
<list :list-data="longList">
  <cell>
    <text>@[title]</text>
    <image src="@[source]">
  </cell>
</list>
```

将上述模板发送到客户端时应该是这样的：

```js
{
  type: 'list',
  attr: {
    listData: [{ title: '', source: '' }, ..., {}]
  }
}
```

```js
{
  type: 'cell',
  children: [{
    type: 'text',
    attr: {
      value: { '@binding': 'title' }
    }
  }, {
    type: 'image',
    attr: {
      src: { '@binding': 'source' }
    }
  }]
}
```

无论列表数据有多长，都将只向 native 发送这两个渲染指令。当列表数据有变化时，只需要重新发送数据，不需要前端框架再次执行渲染。

### 其他说明

在 Rax 中，可以直接写出绑定结构，不需要额外编译。

```html
<list list-data={this.state.longList}>
  <cell>
    <text attr={ { value: { '@binding': 'title' } } }></text>
    <image src={ { '@binding': 'title' } }>
  </cell>
</list>
```

当普通文字和绑定混用时，则应该将其转换为如下格式：

```html
<text>begin @[ content ] end</text>
```

```js
{
  type: 'text',
  attr: {
    value: ['begin ', { '@binding': 'content' }, ' end']
  }
}
```

## 优缺点分析

优势：

+ js 和 native 之间传递的数据量和频率变小。
+ native 实现复用后内存开销变小。

初步实测，性能提升特别明显，尤其在内存占用方面。（数据待补充）

缺陷：

+ 对现有语法改动较大，有破坏性，无论是前端框架还是原生渲染器都需要做大量修改。
+ 容易和现有绑定语法混淆，代码不直观可读性差，在便携式的注意事项也变多了。

**Comment by Hanks10100** [comment]
## 其他语法

### 支持多种子组件类型

在某些情况下，有些列表中的 `<cell>` 的格式并不完全一样，而是分成了几类。这种情况下可以在列表中指定用于标记子组件类型的属性名，在子组件中可以声明自己的类型，这样在渲染时会根据数据类型选择相应的 `<cell>` 模板。

例如：

```html
<list :list-data="longList" template-key="tid">
  <cell template-id="A">
    <text>AAA</text>
  </cell>
  <cell template-id="B">
    <image src="BBB">
  </cell>
  <cell template-id="C">
    <div><text>CCC</text></div>
  </cell>
</list>
```

上述例子声明了三类 `<cell>` 模板，模板类型分别为 `A` 、`B` 、`C`；在 `<list>` 指定了列表数据源 `longList`，还指定了用于判断子节点类型的字段 `template-key="tid"`，即根据每条数据中 `tid` 字段的值判断该渲染的节点类型。

如果给该模板传如下值：

```js
{
  longList: [
    { tid: 'B' },
    { tid: 'A' },
    { tid: 'C' },
    { tid: 'A' },
    { tid: 'C' },
    { tid: 'B' },
    { tid: 'B' }
  ]
}
```

则会渲染生成七个 `<cell>`，格式和顺序是：B A C A C B B 。

## 例子

以 Vue.js 2.0 的语法为例，写法的对比如下：

+ [使用 v-for 渲染列表](http://dotwe.org/vue/8bf0e83e15d647f2ac61c308d11a353d)
+ [由客户端渲染列表](http://dotwe.org/vue/a794866874538b07a3a7724e9d17d496)

使用 v-for 渲染列表，将会产生一条 `createBody(<list>)` 和 200 条 `addElement(<cell>)` 渲染指令，而且每条数据中都包含了相应模板的绑定。

如果由客户端渲染列表，则会产生一条 `createBody(<list>)` 和 3 条 `addElement(<cell>)` 渲染指令，在 `<list>` 组件的属性中包含了列表的数据。

## 潜在问题

### 数据更新

基于目前的绑定方式，即使只更列表中某一条的某一个字段，仍然会触发整个 `list-data` 属性值的更新，会将整个列表数据重新发给 native，native 再 diff 找出更新后的变量。

如果能在更新某一小条数据的时候，把更新数据的路径和新值发给 native 就能优化很多。

### 和其他指令搭配使用

如何与 `v-for` 、`v-if`/`v-else`/`v-else-if` 、`v-bind` 、`v-on` 、`v-once` 、`v-model` 搭配使用，将会有很多细节问题待确定。

**Comment by cxfeng1-zz** [comment]
### 现有的长列表渲染架构

<img width="971" alt="2017-08-08 3 25 06" src="https://user-images.githubusercontent.com/1625893/29066449-d5901706-7bf4-11e7-839b-4141a30eb2fa.png">

### 新的长列表渲染架构

<img width="925" alt="2017-08-08 5 37 35" src="https://user-images.githubusercontent.com/1625893/29066471-e84c9798-7bf4-11e7-9f67-77146b1cca57.png">

**Comment by cxfeng1-zz** [comment]
### 性能

测试机型：iPhone 6， iOS 11，  测试页面： Weex 列表压测页， 所有 Cell 共用一套模板， 每个 cell 有 100+ 个component，同时每个 cell 有 13 处数据绑定：

100 个 Cell(双十一会场体量):

|       |     内存     |   帧率   | 首屏渲染时间 | 峰值CPU占用 |
| :---: | :--------: | :----: | :----: | :-----: |
| 旧渲染架构 | **40.6M**  | 52FPS  |  362   |  162%   |
| 新渲染架构 | **10.4 M** | 59 FPS |  353   |   50%   |
|  提升   |  **74%**   |  14%   |   2%   |   69%   |

500 个 Cell(极限情况):

|       |     内存     |   帧率   | 首屏渲染时间 | 峰值CPU占用 |
| :---: | :--------: | :----: | :----: | :-----: |
| 旧渲染架构 | **190 M**  | 52FPS  |  710   |  182%   |
| 新渲染架构 | **10.9 M** | 59 FPS |  832   |   94%   |
|  提升   |  **94%**   |  14%   |  17%   |   48%   |

整体提升都在意料之中，由于去除了两颗庞大的 DOM 树， 内存上有了质的飞跃， 真正做到了 Native 级别的长列表内存占用；同时由于做到了 View 结构级的复用， 不需要频繁重新创建View，在帧率上也有比较大的提升；另外由于节省了大量 JS 和 Native 的通信时间，首屏渲染时间也有一定的提升，  **越多的cell共用同一个模板，性能提升越明显**。

**Comment by netputer** [comment]
请问一下这个组件有开发计划么？

**Comment by Hanks10100** [comment]
https://github.com/Hanks10100/weex-native-directive

**Comment by netputer** [comment]
在 `0.16` 源码里看到相关实现了，谢谢～
